# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RockYou' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RockYou
	pod 'Firebase/Auth'
	pod 'Firebase/Core'
	pod 'Firebase/Firestore'

	pod 'FSPagerView'
	pod 'SwiftSoup'
end
